// The comparison numbers of the end cards: LEARN_COMPARE[lessonId][model] = { clocks, us, mhz, n }.
// Generated by tools/learn-check.mjs --compare (interface 8 of the design); the values below are
// the ones measured for the design document (section 0) so the letter lesson's compare line is
// never empty before the generator runs.
const LEARN_COMPARE = {
  '8086-01-letter': {
    '8086': { clocks: 34, us: '7.1 µs', mhz: 4.77, n: 4 },
    '80286': { clocks: 28, us: '3.5 µs', mhz: 8, n: 4 },
    '80386': { clocks: 29, us: '1.16 µs', mhz: 25, n: 4 },
    '80486': { clocks: 25, us: '0.76 µs', mhz: 33, n: 4 },
    '80586': { clocks: 20, us: '0.30 µs', mhz: 66, n: 6 },
    '80686': { clocks: 37, us: '0.19 µs', mhz: 200, n: 6 },
  },
};
