// Build the WebAssembly modules: the Pentium Pro model (src/core/p6ooo.c -> p6ooo.wasm.js, constant
// P6OOO_WASM) and the 80386/80486 instruction core (src/core/x86core.c -> x86core.wasm.js, X86CORE_WASM). It needs clang with the wasm32 target (LLVM
// for Windows: C:\Program Files\LLVM\bin\clang.exe; or clang on the PATH). The page does not need
// clang: the generated file is part of the source.
// Usage: node tools/buildwasm.mjs [--clang path] [p6ooo] [x86core]
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const ci = args.indexOf('--clang');
const clang = ci >= 0 ? args[ci + 1] : fs.existsSync('C:/Program Files/LLVM/bin/clang.exe') ? 'C:/Program Files/LLVM/bin/clang.exe' : 'clang';
// the modules: [C source, generated file, JavaScript constant, clang options]
const MODS = [
  ['p6ooo', 'P6OOO_WASM', ['-Wl,--export=ooo', '-Wl,--export=offsets', '-Wl,--export-memory'],
    'The WebAssembly module of the Pentium Pro out-of-order model'],
  // x86core: the memory comes from the machine (x86wasm.js: 336 pages, the guest RAM at 4 MB)
  ['x86core', 'X86CORE_WASM', ['-Wl,--import-memory', '-Wl,--initial-memory=22020096', '-z', 'stack-size=65536', '-Wno-sign-compare',
    '-Wl,--export=ooo', '-Wl,--export=offsets'],
    'The WebAssembly module of the 80386/80486 instruction core'],
];
const only = args.filter(a => !a.startsWith('--') && a !== (ci >= 0 ? args[ci + 1] : null));
for (const [name, konst, opts, what] of MODS) {
  if (only.length && !only.includes(name)) continue;
  const src = path.join(root, `src/core/${name}.c`), tmp = path.join(os.tmpdir(), `${name}.wasm`);
  execFileSync(clang, ['--target=wasm32', '-O3', '-nostdlib', '-Wall', '-Wl,--no-entry', ...opts, '-o', tmp, src], { stdio: 'inherit' });
  const bin = fs.readFileSync(tmp);
  new WebAssembly.Module(bin);            // (a check)
  const out = `// Generated by tools/buildwasm.mjs from src/core/${name}.c: do not change it here.
// ${what} (${bin.length} bytes).
const ${konst} = '${bin.toString('base64')}';
`;
  fs.writeFileSync(path.join(root, `src/core/${name}.wasm.js`), out);
  console.log(`${name}.wasm: ${bin.length} bytes -> src/core/${name}.wasm.js`);
}
