import puppeteer from 'puppeteer-core';
import { pathToFileURL } from 'node:url';
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage();
let errs = 0;
p.on('pageerror', e => { errs++; console.log('pageerror', e.message); });
p.on('console', m => { if (m.type() === 'log') console.log('LOG', m.text()); if (m.type() === 'error') { errs++; console.log('console.error', m.text()); } });
await p.setViewport({ width: 1440, height: 900 });
await p.goto(pathToFileURL('../dist/8086-anatomy.html').href);
await new Promise(r => setTimeout(r, 2500));
await p.click('#btn-popout');
await new Promise(r => setTimeout(r, 1500));
console.log(await p.evaluate(() => JSON.stringify({ pip: !!__app.pip, placeholder: !!document.querySelector('.pip-placeholder'), stageInPip: __app.pip ? !!__app.pip.document.getElementById('stage') : false })));
await p.evaluate(() => { __app.stepInstr(); }); console.log(await p.evaluate(() => { const v = __app.views.board; const c = __app.pip.document.querySelector('#view-board canvas'); const gl = v.renderer && v.renderer.getContext(); const chain = []; for (let e = c; e; e = e.parentElement) { const s = __app.pip.getComputedStyle(e); chain.push((e.id || e.className || e.tagName) + ':' + s.position + ':' + s.display + ':' + e.clientWidth + 'x' + e.clientHeight + ':' + s.inset); } console.log(chain.join(' < ')); const par = c.parentElement, cs = __app.pip.getComputedStyle(par), cc = __app.pip.getComputedStyle(c); return JSON.stringify({ par: [par.className, cs.position, cs.display, par.clientWidth, par.clientHeight], cc: [cc.display, cc.width, cc.position], styles: [...__app.pip.document.querySelectorAll('style')].map(s => s.id || s.textContent.length), canvas: c ? [c.width, c.height, c.clientWidth, c.clientHeight] : null, lost: gl ? gl.isContextLost() : 'n/a', keys: Object.keys(v).slice(0, 40) }); }));
await new Promise(r => setTimeout(r, 1500));
const pages = await b.pages();
console.log('PIX', await p.evaluate(() => { const v = __app.views.board; v.renderer.render(v.scene, v.camera); const gl = v.renderer.getContext(); const px = new Uint8Array(4 * 25); let s = 0; for (let i = 0; i < 5; i++) for (let j = 0; j < 5; j++) { gl.readPixels(Math.floor(gl.drawingBufferWidth * (i + 1) / 6), Math.floor(gl.drawingBufferHeight * (j + 1) / 6), 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, px.subarray(0, 4)); s += px[0] + px[1] + px[2]; } return s + ' buf ' + gl.drawingBufferWidth + 'x' + gl.drawingBufferHeight; })); console.log('pages', pages.length); const pw = pages.find(x => x !== p && x.url() !== 'about:blank') || pages[pages.length - 1]; await pw.setViewport({ width: 1100, height: 720 }).catch(() => {}); await new Promise(r => setTimeout(r, 1200)); await pw.screenshot({ path: 'pop-win.png' }).catch(e => console.log('shot', e.message));
await p.screenshot({ path: 'pop-main.png' });
await p.evaluate(() => __app.pip && __app.pip.close());
await new Promise(r => setTimeout(r, 800));
console.log(await p.evaluate(() => JSON.stringify({ pip: !!__app.pip, back: !!document.querySelector('#layout #pane-stage'), placeholder: !!document.querySelector('.pip-placeholder') })));
console.log('errors', errs);
await b.close();
